language: csharp
solution: Src/Razor-Tools Solution.sln
dotnet: 3.1
mono: none
script:
  - dotnet build Src/Razor-Tools Solution.sln --configuration Release --framework netcoreapp3.1
  - dotnet test Src/Razor-Tools Solution.sln --framework netcoreapp3.1
